export const mockMeetings = [
  {
    id: '1',
    name: 'Q1 Product Strategy Review',
    filename: 'q1-strategy.txt',
    uploaded_at: '2025-04-02T14:30:00Z',
    speakers: ['Sarah Chen', 'James Wilson', 'Maria Rodriguez'],
    word_count: 8764,
    format: 'txt',
    status: 'ready',
    action_items_count: 7,
    decisions_count: 4,
    intel: {
      decisions: [
        { id: 1, decision: 'Accelerate mobile-first redesign to Q2', context: 'User retention metrics show 40% usage via mobile', stakeholders: ['Sarah Chen', 'James Wilson'] },
        { id: 2, decision: 'Allocate 3 engineers to API performance optimization', context: 'Latency increased 200ms YoY; critical path for enterprise clients', stakeholders: ['James Wilson', 'Maria Rodriguez'] },
        { id: 3, decision: 'Delay advanced analytics dashboard to Q3', context: 'Resource constraints; prioritize core functionality', stakeholders: ['Sarah Chen'] },
        { id: 4, decision: 'Adopt new UI framework for consistency', context: 'Current stack fragmented across teams', stakeholders: ['Maria Rodriguez', 'Sarah Chen'] },
      ],
      action_items: [
        { id: 1, task: 'Complete mobile UX audit', owner: 'Sarah Chen', deadline: '2025-04-15', priority: 'High' },
        { id: 2, task: 'Profile API bottlenecks', owner: 'James Wilson', deadline: '2025-04-10', priority: 'High' },
        { id: 3, task: 'Draft framework migration plan', owner: 'Maria Rodriguez', deadline: '2025-04-20', priority: 'Medium' },
        { id: 4, task: 'Coordinate with Sales on enterprise roadmap', owner: 'Sarah Chen', deadline: '2025-04-25', priority: 'Medium' },
        { id: 5, task: 'Schedule async workshop on new patterns', owner: 'Maria Rodriguez', deadline: '2025-04-12', priority: 'Low' },
        { id: 6, task: 'Document decision rationale', owner: 'James Wilson', deadline: '2025-04-18', priority: 'Low' },
        { id: 7, task: 'Review Q2 budget implications', owner: 'Sarah Chen', deadline: '2025-04-22', priority: 'Medium' },
      ],
    },
  },
  {
    id: '2',
    name: 'Engineering All-Hands April',
    filename: 'eng-allhands-apr.vtt',
    uploaded_at: '2025-04-01T10:00:00Z',
    speakers: ['Alex Kumar', 'Jamie Lee', 'Chris Park', 'Sophie Müller'],
    word_count: 12340,
    format: 'vtt',
    status: 'ready',
    action_items_count: 5,
    decisions_count: 3,
    intel: {
      decisions: [
        { id: 1, decision: 'Implement on-call rotation starting May 1st', context: 'Current system unsustainable; burnout risk identified', stakeholders: ['Alex Kumar', 'Jamie Lee'] },
        { id: 2, decision: 'Mandatory security training for all engineers', context: 'Recent incident revealed gaps in vulnerability awareness', stakeholders: ['Chris Park', 'Sophie Müller'] },
        { id: 3, decision: 'Deprecate legacy payment service by EOY', context: 'Maintenance burden exceeds benefits; replacement complete', stakeholders: ['Jamie Lee', 'Chris Park'] },
      ],
      action_items: [
        { id: 1, task: 'Design on-call escalation policies', owner: 'Alex Kumar', deadline: '2025-04-20', priority: 'High' },
        { id: 2, task: 'Procure security training platform', owner: 'Sophie Müller', deadline: '2025-04-15', priority: 'High' },
        { id: 3, task: 'Plan legacy service migration', owner: 'Chris Park', deadline: '2025-05-01', priority: 'Medium' },
        { id: 4, task: 'Set up monitoring for new on-call system', owner: 'Jamie Lee', deadline: '2025-04-25', priority: 'Medium' },
        { id: 5, task: 'Communicate timeline to stakeholders', owner: 'Alex Kumar', deadline: '2025-04-10', priority: 'Low' },
      ],
    },
  },
  {
    id: '3',
    name: 'Client Success: Acme Corp Debrief',
    filename: 'acme-debrief.txt',
    uploaded_at: '2025-03-31T16:45:00Z',
    speakers: ['Nina Thompson', 'Robert Chang', 'Emma Walsh'],
    word_count: 5230,
    format: 'txt',
    status: 'processing',
    action_items_count: 0,
    decisions_count: 0,
    intel: null,
  },
]

export const mockBrief = {
  classification: 'UNCLASSIFIED',
  threat_level: 'YELLOW',
  threat_reason: 'Multiple medium-priority action items with overlapping deadlines pose execution risk.',
  headline: 'Q1 Product Pivot: Mobile-First & Performance Optimization',
  situation: 'Organization is shifting focus to mobile user experience and backend API performance. Key constraint: limited engineering capacity requires prioritization and phased rollout.',
  key_intel: [
    'Mobile usage now 40% of total; retention differential suggests untapped growth',
    'API latency increased 200ms YoY; impacting enterprise customer satisfaction',
    'UI framework fragmentation across teams is technical debt risk',
    '3 critical decisions made; 7 action items assigned with high confidence',
  ],
  orders: [
    'Execute mobile UX audit by April 15 — gates design sprint',
    'Complete API profiling by April 10 — informs optimization roadmap',
    'Socialize framework migration plan with team leads by April 20',
    'Allocate 3 FTEs to performance track through Q2',
  ],
  risk_flags: [
    'Sarah Chen overloaded: 3 critical assignments; mitigate with async ownership',
    'Q3 analytics feature deprioritization may conflict with sales commitments',
    'Mobile redesign scope unclear; recommend design kickoff within 48h',
  ],
}
